### Invio Notification
POST  http://localhost:4004/notificaton-servive-call/notification  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{"NotificationPayload" :
    {
        "area"      : "2e0d8f14-59d7-4020-b91c-bfec1a53ff3f",
        "alertBusinessTime" : "2020-11-24T09:40:43.327Z",
        "alertCode" : "LOG_ALERT", 
        "alertLevel" : "1", 
        "payload"  : "{\"entityType\":\"SEGMENT\",\"action\":\"OPEN\",\"entityId\":\"c8c61bc1-5076-4064-8769-8d0b78a6b71a\",\"entityURL\":\"https://sap-iot-noah-live-segment-service.cfapps.eu10.hana.ondemand.com/v1/segments/c8c61bc1-5076-4064-8769-8d0b78a6b71a\"}",
        "GUID" : "{{$guid}}"
    }
}