### Create ControlPoint
POST http://localhost:4004/handling-unit-moved/ControlPoints  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
    "ID": "90abe75c-e2c6-4e5f-a12f-fb81aa50d011"
}



### Create ControlPoint REMOTE
POST http://localhost:4004/handling-unit-moved/ControlPoints  HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ID": "90abe75c-e2c6-4e5f-a12f-fb81aa50d011"
}

### Create HandlingUnit
POST http://localhost:4004/handling-unit-moved/HandlingUnits  HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ID": "TEST1234"
}

### Create Product
POST http://localhost:4004/services/Products  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
    "ID": "105c5d53-9123-4775-b836-ddf8e6951bd1",
    "gtin": "1234567890123"
}

### Create Lot
POST http://localhost:4004/services/Lots  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
    "ID": "728985ee-301e-45be-bffa-e8b2eb7a3683",
    "name": "lotto1",
    "product_ID": "105c5d53-9123-4775-b836-ddf8e6951bd1"
}

### Create HandlingUnit
POST http://localhost:4004/services/HandlingUnits  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
	"ID": "2b3b3fbc-da34-452a-876e-75c337a549ef",
	"lot_ID": "728985ee-301e-45be-bffa-e8b2eb7a3683",
    "MSG_ID":"2b3b3fbc-da34-452a-876e-75c337a549ef"
}


### GET HandlingUnit
GET  http://localhost:4004/services/HandlingUnits  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

### Create HandlingUnitsRawMovements
POST http://localhost:4004/handling-unit-moved/HandlingUnitsRawMovements HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
    "MSG_ID":"zz4ce6f3-283c-4a95-8470-c3664ebddbd0",
    "CP_ID": "90abe75c-e2c6-4e5f-a12f-fb81aa50d011",
    "TE": "1900-10-14T09:01:33.763Z",
    "TS": "1900-10-14T09:01:34.763Z",
    "HU_ID": "123456789012345678",
    "DIR": "F"
}


### Get HandlingUnitsRawMovements
GET http://localhost:4004/handling-unit-moved/HandlingUnitsRawMovements HTTP/1.1
Authorization: Basic Alice:Alice


# --------------------------------------------------------------------
# --------------------------------------------------------------------
# --------------------------------------------------------------------
# --------------------------------------------------------------------

### Create HandlingUnitsMovements ---------------------- DO NOT USE -----------------
POST http://localhost:4004/handling-unit-moved/HandlingUnitsMovements HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
    "MSG_ID":"994ce6f3-283c-4a95-8470-c3664ebddbd0",
    "controlPoint_ID": "90abe75c-e2c6-4e5f-a12f-fb81aa50d011",
    "TE": "1900-10-14T09:01:33.763Z",
    "TS": "1900-10-14T09:01:34.763Z",
    "handlingUnit_ID": "51ca3a4d-45a1-449b-820c-f7a378ac8c8c",
    "DIR": "F"
}


### GET HandlingUnitsMovements---------------------- DO NOT USE -----------------
GET http://localhost:4004/handling-unit-moved/HandlingUnitsMovements HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json


@customera-subdomain = ccp-customera

@token = {{getToken.response.body.$.access_token}}

### Get bearer token
# @name getToken
GET https://{{customera-subdomain}}.authentication.eu10.hana.ondemand.com/oauth/token?grant_type=client_credentials&response_type=token HTTP/1.1
Authorization: Basic sb-ccp-provider-dev-qas-dev-cloud-cold-chain!t61773 oEPmeoq3s9kvPuGZsd89POK9Eo8=

### E' possibile collegare il cap locale al db hana in cloud! esempio get
GET http://localhost:4004/handling-unit-moved/HandlingUnitsRawMovements/$count HTTP/1.1
Authorization: Bearer {{token}}

### Create HandlingUnitsRawMovements nel db hana in cloud
POST http://localhost:4004/handling-unit-moved/HandlingUnitsRawMovements HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
 
{
    "MSG_ID":"994ce6f3-283c-4a95-8470-c3664ebddbd0",
    "CP_ID": "90abe75c-e2c6-4e5f-a12f-fb81aa50d011",
    "TE": "2020-10-14T09:01:33.763Z",
    "TS": "2020-10-14T09:01:34.763Z",
    "HU_ID": "123456789012345678",
    "DIR": "B"
}

### Recupera books
GET http://localhost:4004/handling-unit-moved/Books  HTTP/1.1
Authorization: Basic Alice:Alice

### Creazione record Books
POST http://localhost:4004/handling-unit-moved/Books  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
    "CP_ID": "90abe75c-e2c6-4e5f-a12f-fb81aa50d011",
    "TE": "2020-10-14T09:01:33.763Z",
    "TS": "2020-10-14T09:01:34.763Z",
    "HU_ID": "TEST1234",
    "DIR": "B"
}

### Aggionamento Book con etag
PATCH http://localhost:4004/handling-unit-moved/Books(ID=c6d90577-3f1b-438e-95a1-f02bfbffafad)  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json
If-Match: "2020-11-01T15:48:57.600Z"

{
    "MSG_ID":"994ce6f3-283c-4a95-8470-c3664ebddbd0",
    "CP_ID": "a0abe75c-e2c6-4e5f-a12f-fb81aa50d011",
    "TE": "2020-10-14T09:01:33.763Z",
    "TS": "2020-10-14T09:01:34.763Z",
    "HU_ID": "TEST1234",
    "DIR": "F"
}