@customera-subdomain = ccp-customera

@token = {{getToken.response.body.$.access_token}}

### Create HandlingUnitsRawMovements
POST http://localhost:4004/handling-unit-moved/HandlingUnitsRawMovements HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
	"CP_ID": "{{$guid}}",
    "TE": "1904-10-14T09:01:33.763Z",
	"TS": "1905-10-14T09:01:34.763Z",
    "SSCC_ID": "TEST123",
    "DIR": "T"
}


### Get HandlingUnitsRawMovements
GET http://localhost:4004/handling-unit-moved/HandlingUnitsRawMovements HTTP/1.1
Authorization: Basic Alice:Alice


### Get bearer token
# @name getToken
GET https://{{customera-subdomain}}.authentication.eu10.hana.ondemand.com/oauth/token?grant_type=client_credentials&response_type=token HTTP/1.1
Authorization: Basic sb-dev-cloud-cold-chain!t61773 I4pSt9LZ2ar5djKL7lB518ZWV6s=


### E' possibile collegare il cap locale al db hana in cloud! esempio get
GET http://localhost:4004/handling-unit-moved/HandlingUnitsRawMovements HTTP/1.1
Authorization: Bearer {{token}}

### Create HandlingUnitsRawMovements nel db hana in cloud
POST http://localhost:4004/handling-unit-moved/HandlingUnitsRawMovements HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
 
{
	"CP_ID": "{{$guid}}",
    "TE": "2020-10-14T09:01:33.763Z",
	"TS": "2020-10-14T09:01:34.763Z",
    "SSCC_ID": "123456789012345678",
    "DIR": "B"
}



### Creazione record Books
POST http://localhost:4004/handling-unit-moved/Books  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
	"CP_ID": "90abe75c-e2c6-4e5f-a12f-fb81aa50d011",
    "TE": "2020-10-14T09:01:33.763Z",
	"TS": "2020-10-14T09:01:34.763Z",
    "SSCC_ID": "123456789012345678",
    "DIR": "B"
}

### Create ControlPoint
POST http://localhost:4004/handling-unit-moved/ControlPoints  HTTP/1.1
Authorization: Basic Alice:Alice
Content-Type: application/json

{
	"ID": "90abe75c-e2c6-4e5f-a12f-fb81aa50d011"
}